import { Market } from "../types/trading";

export const RWA_MARKETS: Market[] = [
  {
    id: "BTCUSDT",
    name: "Bitcoin",
    symbol: "BTC/USDT",
    price: 0,
    change24h: 0,
    volume24h: 0,
    category: "Crypto",
    fundingRate: 0.01,
    borrowRate: 0.05,
  },
  {
    id: "ETHUSDT",
    name: "Ethereum",
    symbol: "ETH/USDT",
    price: 0,
    change24h: 0,
    volume24h: 0,
    category: "Crypto",
    fundingRate: 0.01,
    borrowRate: 0.05,
  },
  {
    id: "SOLUSDT",
    name: "Solana",
    symbol: "SOL/USDT",
    price: 0,
    change24h: 0,
    volume24h: 0,
    category: "Crypto",
    fundingRate: 0.012,
    borrowRate: 0.06,
  },
  {
    id: "BNBUSDT",
    name: "BNB",
    symbol: "BNB/USDT",
    price: 0,
    change24h: 0,
    volume24h: 0,
    category: "Crypto",
    fundingRate: 0.01,
    borrowRate: 0.04,
  },
];
