import { Market } from "../types/trading";

export const RWA_MARKETS: Market[] = [
  {
    id: "xau-usd",
    name: "Gold",
    symbol: "XAU/USD",
    price: 2384.45,
    change24h: 1.25,
    category: "Commodity",
    fundingRate: 0.01,
    borrowRate: 0.05,
  },
  {
    id: "xag-usd",
    name: "Silver",
    symbol: "XAG/USD",
    price: 28.14,
    change24h: -0.45,
    category: "Commodity",
    fundingRate: 0.008,
    borrowRate: 0.04,
  },
  {
    id: "eur-usd",
    name: "Euro / USD",
    symbol: "EUR/USD",
    price: 1.0854,
    change24h: 0.12,
    category: "Forex",
    fundingRate: 0.005,
    borrowRate: 0.02,
  },
  {
    id: "wti-oil",
    name: "Crude Oil",
    symbol: "WTI",
    price: 85.32,
    change24h: 2.14,
    category: "Commodity",
    fundingRate: 0.015,
    borrowRate: 0.06,
  },
  {
    id: "spx-500",
    name: "S&P 500",
    symbol: "SPX",
    price: 5214.30,
    change24h: 0.85,
    category: "Stocks",
    fundingRate: 0.01,
    borrowRate: 0.03,
  },
];
